# File: .github/workflows/request_production_approval.yml
name: Request Production Approval

on:
  workflow_call:
    inputs:
      proxy_name:
        required: true
        type: string
      version_id:
        required: true
        type: string
      revision:
        required: true
        type: string
    outputs:
      revision:
        description: "The approved revision number"
        value: ${{ inputs.revision }}
      version_id:
        description: "The approved version ID"
        value: ${{ inputs.version_id }}

jobs:
  request_approval:
    runs-on: ubuntu-latest
    environment:
      name: production-approval
    steps:
      - name: Set Deployment Status
        run: |
          echo "::group::👥 Production Deployment Request"
          echo "✅ Non-prod deployment successful"
          echo "⏳ Awaiting production approval"
          echo "📦 Proxy: ${{ inputs.proxy_name }}"
          echo "📝 Revision: ${{ inputs.revision }}"
          echo "🏷️ Version ID: ${{ inputs.version_id }}"
          echo "::endgroup::"

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: proxy-artifacts-${{ inputs.version_id }}
          path: artifacts

      - name: List Downloaded Artifacts
        run: |
          echo "::group::📦 Production Deployment Artifacts"
          echo "Verifying artifacts..."
          ls -la artifacts/
          echo "📝 Source revision: $(cat artifacts/revision.txt)"
          echo "✅ Artifacts verified successfully"
          echo "::endgroup::"
