name: Setup Authentication

on:
  workflow_call:
    secrets:
      secrets_yml:
        required: true

jobs:
  Setup_Auth:
    runs-on: ubuntu-latest
    env:
      APIGEE_ORG: ${{ secrets.secrets_yml.APIGEE_ORG }}
      APIGEE_ORG_PROD: ${{ secrets.secrets_yml.APIGEE_ORG_PROD }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.secrets_yml.WORKLOAD_IDENTITY_PROVIDER }}
      WORKLOAD_IDENTITY_PROVIDER_PROD: ${{ secrets.secrets_yml.WORKLOAD_IDENTITY_PROVIDER_PROD }}
      SERVICE_ACCOUNT: ${{ secrets.secrets_yml.SERVICE_ACCOUNT }}
      SERVICE_ACCOUNT_PROD: ${{ secrets.secrets_yml.SERVICE_ACCOUNT_PROD }}
    
    steps:
      - name: Set up job
        run: |
          echo "::group::🔐 Setting up Authentication"
          echo "Initializing authentication process..."

      - name: Non-Prod Authentication
        id: nonprod_auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          token_format: access_token
          create_credentials_file: true

      - name: Post Non-Prod Authentication
        run: |
          echo "✅ Non-prod authentication completed successfully"

      - name: Prod Authentication
        id: prod_auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_PROD }}
          token_format: access_token
          create_credentials_file: true

      - name: Complete job
        run: |
          echo "✅ Authentication setup completed for all environments"
          echo "::endgroup::"
