name: Validate API Proxy

on:
  workflow_call:
    inputs:
      proxy_directory:
        description: Working directory to zip up as your proxy bundle
        required: false
        type: string
        default: apiproxy
    secrets:
      SERVICE_ACCOUNT:
        required: true
      SERVICE_ACCOUNT_PROD:
        required: true

jobs:
  Validate_API_Proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install apigeelint
        run: |
          echo "::group::🔍 Installing API Proxy Validator"
          npm install -g apigeelint
          if [ $? -ne 0 ]; then
            echo "❌ Failed to install apigeelint"
            exit 1
          fi
          echo "✅ apigeelint installed successfully"
          echo "::endgroup::"

      - name: Run apigeelint
        run: |
          echo "::group::🔍 Validating API Proxy"
          echo "Running apigeelint validation..."
          apigeelint -s ${{ inputs.proxy_directory }} -f table.js
          if [ $? -ne 0 ]; then
            echo "❌ API proxy validation failed"
            exit 1
          fi
          echo "✅ API proxy validation passed"
          echo "::endgroup::"