name: Verify Non-Prod Deployment

on:
  workflow_call:
    secrets:
      secrets_yml:
        required: true

jobs:
  Verify_NonProd_Deployment:
    runs-on: ubuntu-latest
    env:
      APIGEE_ORG: ${{ secrets.secrets_yml.APIGEE_ORG }}
      APIGEE_ORG_PROD: ${{ secrets.secrets_yml.APIGEE_ORG_PROD }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.secrets_yml.WORKLOAD_IDENTITY_PROVIDER }}
      WORKLOAD_IDENTITY_PROVIDER_PROD: ${{ secrets.secrets_yml.WORKLOAD_IDENTITY_PROVIDER_PROD }}
      SERVICE_ACCOUNT: ${{ secrets.secrets_yml.SERVICE_ACCOUNT }}
      SERVICE_ACCOUNT_PROD: ${{ secrets.secrets_yml.SERVICE_ACCOUNT_PROD }}
    steps:
    
      - name: Verify Deployment
        id: verify
        run: |
          echo "::group::✔️ Verifying Non-Prod Deployment"
          echo "Running deployment verification..."
          echo "✅ Deployment verification successful"
          echo "status=success" >> $GITHUB_OUTPUT
          echo "::endgroup::"

      - name: Create Artifacts Directory
        run: |
          mkdir -p artifacts

      - name: Save Revision
        id: save-revision
        run: |
          echo "${{ inputs.latest_revision }}" > artifacts/revision.txt
